# Recommendation Systems - KNN

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np

In [3]:
r_columns=['user_id','movie_id','rating']
ratings = pd.read_csv('ml-100k/u.data',sep="\t",header=None,usecols=range(3),names=r_columns)

In [4]:
ratings.head()

   user_id  movie_id  rating
0      196       242       3
1      186       302       3
2       22       377       1
3      244        51       2
4      166       346       1

In [5]:
r_cols=["movie_id","title"]
movies=pd.read_csv('ml-100k/u.item', encoding='ISO-8859-1',sep='|',header=None,names=r_cols, usecols=range(2))
movies.head()

   movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [6]:
#Cosine Distance

In [9]:
movie_properties=ratings.groupby("movie_id").agg({"rating":[np.size,np.mean]})

In [10]:
movie_properties.head()

         rating
           size      mean
movie_id
1           452  3.878319
2           131  3.206107
3            90  3.033333
4           209  3.550239
5            86  3.302326

In [11]:
df=pd.read_csv("ml-100k/u.item",sep="|",header=None,encoding="ISO-8859-1")

In [12]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [14]:
movie_dict={}
with open ('ml-100k/u.item',encoding='iso-8859-1') as f:
    for line in f:
        fields=line.rstrip('\n').split('|')
        movie_id=int(fields[0])
        name=fields[1]
        genres=fields[5:24]
        genres=list(map(int,genres))
        movie_dict[movie_id]=(name,genres,movie_properties.loc[movie_id].rating.get('size'),movie_properties.loc[movie_id].rating.get('mean'))

In [15]:
from scipy import spatial
def compute_distance(a,b):
    genre_distance=spatial.distance.cosine(a[1],b[1])
    popularity_distance=abs(a[2]-b[2])
    return genre_distance+popularity_distance

In [16]:
movie_dict[2]

('GoldenEye (1995)',
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
 131.0,
 3.2061068702290076)

In [17]:
movie_dict[4]

('Get Shorty (1995)',
 [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 209.0,
 3.550239234449761)

In [18]:
compute_distance(movie_dict[2],movie_dict[4])

78.66666666666667

In [21]:
mesafeler=[]
for movie1 in movie_dict:
    for movie2 in movie_dict:
        mesafeler.append(compute_distance(movie_dict[movie1],movie_dict[movie2]))

In [24]:
mesafeler

[0.0,
 322.0,
 363.0,
 243.66666666666666,
 367.0,
 427.0,
 61.0,
 233.33333333333334,
 154.0,
 364.0,
 217.0,
 186.0,
 268.42264973081035,
 270.0,
 160.0,
 413.59175170953614,
 360.7418011102528,
 443.0,
 384.0,
 381.0,
 368.7418011102528,
 156.0,
 271.0,
 279.0,
 159.42264973081038,
 379.42264973081035,
 396.0,
 177.0,
 338.7113248654052,
 416.0,
 299.0,
 372.0,
 356.0,
 445.59175170953614,
 441.6666666666667,
 440.0,
 445.0,
 333.0,
 366.0,
 395.42264973081035,
 415.42264973081035,
 304.42264973081035,
 413.0,
 374.0,
 372.59175170953614,
 426.0,
 319.59175170953614,
 336.0,
 371.59175170953614,
 132.0,
 372.0,
 362.0,
 325.0,
 349.0,
 304.0,
 59.0,
 413.0,
 278.0,
 370.0,
 389.0,
 394.0,
 326.0,
 370.1835034190723,
 170.0,
 337.59175170953614,
 290.59175170953614,
 349.42264973081035,
 319.0,
 131.66666666666666,
 201.59175170953614,
 232.33333333333334,
 323.6666666666667,
 324.6666666666667,
 445.6666666666667,
 448.0,
 399.0,
 302.0,
 419.6666666666667,
 117.0,
 384.6666666666667,
 342.59175170953614,
 192.0,
 276.59175170953614,
 435.0,
 394.42264973081035,
 303.0,
 315.0,
 239.59175170953614,
 178.0,
 357.6666666666667,
 309.3333333333333,
 349.0,
 340.59175170953614,
 315.1835034190723,
 233.13397459621555,
 158.0,
 197.0,
 63.0,
 280.3333333333333,
 57.0,
 379.7418011102528,
 398.1835034190723,
 437.3333333333333,
 447.42264973081035,
 378.42264973081035,
 382.0,
 411.0,
 387.42264973081035,
 322.59175170953614,
 421.7113248654052,
 180.59175170953614,
 432.59175170953614,
 444.0,
 385.42264973081035,
 438.0,
 327.42264973081035,
 75.0,
 160.0,
 449.0,
 385.59175170953614,
 24.0,
 346.42264973081035,
 337.59175170953614,
 266.0,
 209.0,
 356.0,
 40.0,
 388.0,
 324.0,
 430.0,
 358.0,
 206.71132486540517,
 282.0,
 255.0,
 194.0,
 348.0,
 282.0,
 433.1835034190723,
 402.1835034190723,
 391.59175170953614,
 380.7113248654052,
 395.6666666666667,
 231.0,
 210.0,
 388.0,
 443.0,
 268.0,
 325.0,
 430.0,
 295.59175170953614,
 126.33333333333333,
 370.59175170953614,
 205.42264973081038,
 278.42264973081035,
 355.0,
 305.0,
 326.0,
 392.42264973081035,
 352.0,
 384.0,
 233.0,
 347.0,
 360.42264973081035,
 302.0,
 389.0,
 395.0,
 385.42264973081035,
 136.42264973081038,
 334.1835034190723,
 331.6666666666667,
 387.59175170953614,
 86.0,
 128.71132486540517,
 33.0,
 245.0,
 169.0,
 316.0,
 328.0,
 232.0,
 232.0,
 56.0,
 227.0,
 162.0,
 336.7418011102528,
 214.0,
 201.66666666666666,
 244.0,
 283.0,
 386.1835034190723,
 329.0,
 177.0,
 337.0,
 296.0,
 211.59175170953614,
 152.0,
 202.0,
 214.0,
 326.0,
 288.0,
 247.0,
 363.7113248654052,
 172.59175170953614,
 271.0,
 102.59175170953614,
 317.0,
 402.7113248654052,
 387.0,
 252.59175170953614,
 261.6666666666667,
 122.0,
 246.59175170953614,
 361.0,
 319.0,
 339.0,
 241.0,
 162.59175170953614,
 333.0,
 282.0,
 342.0,
 386.59175170953614,
 379.0,
 88.0,
 317.0,
 409.0,
 343.1835034190723,
 287.0,
 292.0,
 209.0,
 282.0,
 254.0,
 310.7113248654052,
 351.6666666666667,
 329.0,
 173.0,
 235.71132486540517,
 407.59175170953614,
 69.0,
 196.42264973081038,
 303.0,
 296.1835034190723,
 325.0,
 335.42264973081035,
 320.1835034190723,
 405.0,
 213.0,
 329.0,
 447.6666666666667,
 292.59175170953614,
 322.42264973081035,
 256.0,
 406.42264973081035,
 295.0,
 427.0,
 391.0,
 280.59175170953614,
 436.59175170953614,
 149.71132486540517,
 58.0,
 290.1835034190723,
 326.0,
 409.1835034190723,
 387.0,
 434.0,
 352.0,
 226.0,
 418.0,
 444.0,
 198.0,
 137.42264973081038,
 317.0,
 242.0,
 255.0,
 230.0,
 262.59175170953614,
 185.0,
 155.0,
 382.0,
 393.0,
 425.0,
 368.0,
 307.0,
 221.0,
 276.0,
 259.59175170953614,
 291.0,
 30.0,
 375.0,
 27.0,
 194.0,
 356.42264973081035,
 326.0,
 339.0,
 306.0,
 33.42264973081038,
 376.0,
 447.0,
 403.0,
 259.0,
 380.0,
 22.0,
 222.42264973081038,
 156.0,
 319.0,
 303.59175170953614,
 366.0,
 357.0,
 265.0,
 422.6666666666667,
 425.0,
 308.0,
 378.0,
 372.7113248654052,
 103.0,
 447.59175170953614,
 293.0,
 340.59175170953614,
 351.0,
 155.0,
 284.6666666666667,
 433.0,
 283.42264973081035,
 235.0,
 213.0,
 328.0,
 325.0,
 278.0,
 278.0,
 158.0,
 408.0,
 412.0,
 340.0,
 310.0,
 202.0,
 389.0,
 431.42264973081035,
 410.0,
 434.6666666666667,
 361.42264973081035,
 406.0,
 264.0,
 441.42264973081035,
 400.59175170953614,
 329.0,
 398.0,
 387.59175170953614,
 327.0,
 315.59175170953614,
 426.0,
 422.0,
 412.0,
 433.0,
 426.59175170953614,
 439.0,
 380.59175170953614,
 412.0,
 356.0,
 189.0,
 310.0,
 435.0,
 443.0,
 443.0,
 424.6666666666667,
 406.0,
 415.42264973081035,
 405.0,
 406.0,
 282.42264973081035,
 421.42264973081035,
 397.42264973081035,
 414.0,
 386.0,
 418.42264973081035,
 414.0,
 441.59175170953614,
 430.0,
 428.42264973081035,
 439.1835034190723,
 352.0,
 410.0,
 337.0,
 352.59175170953614,
 341.59175170953614,
 421.1835034190723,
 383.42264973081035,
 244.71132486540517,
 365.42264973081035,
 388.0,
 424.59175170953614,
 425.59175170953614,
 442.42264973081035,
 393.59175170953614,
 385.0,
 260.42264973081035,
 440.6666666666667,
 396.42264973081035,
 398.6666666666667,
 441.0,
 426.7113248654052,
 363.6666666666667,
 434.1835034190723,
 376.42264973081035,
 282.6666666666667,
 252.0,
 351.1835034190723,
 109.0,
 404.0,
 409.42264973081035,
 340.3333333333333,
 382.59175170953614,
 290.42264973081035,
 289.7113248654052,
 359.42264973081035,
 398.0,
 390.42264973081035,
 427.3333333333333,
 388.59175170953614,
 379.59175170953614,
 323.3333333333333,
 274.3333333333333,
 371.3333333333333,
 347.0,
 426.0,
 152.71132486540517,
 434.0,
 367.42264973081035,
 420.52859547920895,
 234.0,
 331.42264973081035,
 356.0,
 359.59175170953614,
 300.0,
 278.3333333333333,
 281.42264973081035,
 386.0,
 236.66666666666666,
 354.0,
 448.0,
 447.0,
 448.0,
 439.0,
 400.0,
 449.0,
 291.0,
 407.0,
 431.0,
 444.0,
 332.0,
 368.0,
 336.0,
 390.0,
 282.6666666666667,
 387.0,
 437.0,
 437.0,
 308.0,
 404.59175170953614,
 425.6666666666667,
 363.0,
 429.0,
 425.0,
 379.0,
 305.0,
 382.0,
 426.0,
 367.6666666666667,
 401.0,
 405.0,
 389.0,
 386.0,
 345.0,
 232.0,
 295.0,
 326.3333333333333,
 259.0,
 203.0,
 292.42264973081035,
 357.1835034190723,
 348.59175170953614,
 274.0,
 273.59175170953614,
 389.59175170953614,
 324.59175170953614,
 210.0,
 315.0,
 328.0,
 388.59175170953614,
 384.59175170953614,
 388.0,
 401.0,
 402.6666666666667,
 386.0,
 394.0,
 393.0,
 396.42264973081035,
 393.59175170953614,
 222.0,
 384.42264973081035,
 301.0,
 391.0,
 421.59175170953614,
 329.3333333333333,
 395.59175170953614,
 414.0,
 331.0,
 385.0,
 363.0,
 355.0,
 238.0,
 332.0,
 332.0,
 280.0,
 395.6666666666667,
 381.0,
 272.59175170953614,
 252.0,
 389.42264973081035,
 361.6666666666667,
 364.0,
 373.0,
 329.0,
 333.0,
 417.59175170953614,
 288.59175170953614,
 406.42264973081035,
 380.0,
 329.0,
 258.0,
 332.0,
 360.0,
 373.0,
 324.0,
 431.0,
 438.0,
 440.0,
 398.59175170953614,
 443.0,
 423.0,
 386.3333333333333,
 408.1835034190723,
 410.0,
 404.0,
 401.42264973081035,
 432.0,
 382.0,
 440.59175170953614,
 199.0,
 412.0,
 440.59175170953614,
 361.0,
 302.0,
 429.0,
 408.0,
 390.0,
 351.0,
 443.0,
 441.0,
 436.0,
 383.0,
 316.0,
 430.52859547920895,
 394.0,
 405.0,
 424.0,
 425.59175170953614,
 431.0,
 274.0,
 418.0,
 223.0,
 386.0,
 403.0,
 424.59175170953614,
 424.0,
 420.0,
 438.0,
 408.59175170953614,
 360.0,
 411.59175170953614,
 361.0,
 433.42264973081035,
 420.59175170953614,
 394.0,
 285.0,
 416.0,
 373.59175170953614,
 413.42264973081035,
 419.0,
 439.0,
 250.33333333333334,
 410.0,
 435.0,
 275.0,
 444.0,
 441.0,
 448.0,
 389.0,
 325.3333333333333,
 247.0,
 448.59175170953614,
 452.0,
 450.42264973081035,
 433.0,
 403.0,
 244.0,
 371.42264973081035,
 422.0,
 387.0,
 387.0,
 423.0,
 392.42264973081035,
 412.0,
 413.0,
 419.0,
 425.42264973081035,
 402.0,
 394.0,
 389.0,
 435.0,
 435.0,
 389.0,
 410.0,
 442.0,
 413.59175170953614,
 413.1835034190723,
 430.3333333333333,
 370.1835034190723,
 448.59175170953614,
 378.0,
 284.0,
 375.59175170953614,
 421.59175170953614,
 334.0,
 395.0,
 384.0,
 429.0,
 430.0,
 362.0,
 414.59175170953614,
 409.0,
 413.0,
 371.0,
 420.0,
 364.0,
 449.0,
 418.0,
 426.0,
 415.0,
 383.0,
 385.59175170953614,
 403.0,
 381.0,
 282.0,
 362.59175170953614,
 419.0,
 306.0,
 225.66666666666666,
 409.0,
 322.0,
 374.0,
 337.6666666666667,
 300.0,
 365.0,
 371.0,
 336.42264973081035,
 407.0,
 353.0,
 448.0,
 441.0,
 447.0,
 440.0,
 417.0,
 407.0,
 388.0,
 367.0,
 405.0,
 399.0,
 376.0,
 452.0,
 234.0,
 346.0,
 419.0,
 426.0,
 353.0,
 403.42264973081035,
 284.0,
 296.0,
 403.0,
 383.59175170953614,
 408.42264973081035,
 366.0,
 298.0,
 437.0,
 288.6666666666667,
 362.0,
 409.0,
 439.59175170953614,
 374.0,
 413.0,
 443.0,
 351.0,
 437.42264973081035,
 443.0,
 399.59175170953614,
 434.0,
 429.0,
 316.0,
 447.0,
 383.0,
 352.0,
 348.59175170953614,
 373.42264973081035,
 452.0,
 401.59175170953614,
 381.0,
 440.0,
 365.59175170953614,
 395.0,
 371.0,
 436.42264973081035,
 423.59175170953614,
 367.0,
 398.42264973081035,
 394.42264973081035,
 418.59175170953614,
 377.0,
 436.42264973081035,
 438.59175170953614,
 390.0,
 407.59175170953614,
 372.0,
 429.0,
 413.6666666666667,
 272.59175170953614,
 438.0,
 425.42264973081035,
 316.0,
 375.0,
 393.59175170953614,
 421.59175170953614,
 288.59175170953614,
 390.0,
 395.0,
 186.0,
 414.0,
 361.0,
 436.42264973081035,
 333.42264973081035,
 350.59175170953614,
 137.0,
 401.59175170953614,
 329.0,
 273.0,
 414.0,
 429.0,
 396.0,
 356.7418011102528,
 324.42264973081035,
 449.0,
 432.0,
 442.0,
 407.0,
 409.0,
 338.0,
 303.42264973081035,
 423.59175170953614,
 420.59175170953614,
 444.0,
 442.0,
 400.59175170953614,
 411.0,
 396.0,
 412.0,
 404.0,
 436.0,
 421.0,
 426.6666666666667,
 444.0,
 449.0,
 376.6666666666667,
 422.0,
 383.42264973081035,
 368.59175170953614,
 443.0,
 415.59175170953614,
 451.0,
 413.59175170953614,
 438.59175170953614,
 439.59175170953614,
 450.0,
 405.59175170953614,
 386.42264973081035,
 442.42264973081035,
 366.42264973081035,
 442.42264973081035,
 407.0,
 431.1835034190723,
 416.59175170953614,
 422.0,
 444.0,
 448.0,
 427.0,
 436.42264973081035,
 413.0,
 444.0,
 444.42264973081035,
 425.59175170953614,
 403.0,
 444.0,
 422.0,
 410.0,
 408.0,
 435.0,
 434.59175170953614,
 397.0,
 452.0,
 341.0,
 432.0,
 450.0,
 427.42264973081035,
 412.42264973081035,
 359.2254033307585,
 430.59175170953614,
 449.0,
 371.0,
 403.42264973081035,
 370.0,
 373.0,
 396.0,
 439.59175170953614,
 419.0,
 452.0,
 362.0,
 430.6666666666667,
 404.0,
 428.0,
 437.6666666666667,
 426.59175170953614,
 428.0,
 449.0,
 449.0,
 400.0,
 405.0,
 425.3333333333333,
 422.1835034190723,
 411.0,
 276.42264973081035,
 409.0,
 398.0,
 444.0,
 400.0,
 449.0,
 449.0,
 452.0,
 438.59175170953614,
 436.59175170953614,
 387.0,
 416.59175170953614,
 452.0,
 450.0,
 437.59175170953614,
 437.0,
 450.0,
 434.3333333333333,
 429.0,
 366.42264973081035,
 432.0,
 333.59175170953614,
 447.0,
 448.0,
 428.59175170953614,
 444.0,
 377.42264973081035,
 411.0,
 371.59175170953614,
 414.0,
 400.0,
 405.59175170953614,
 401.0,
 419.3333333333333,
 317.0,
 394.0,
 407.59175170953614,
 419.0,
 440.0,
 446.0,
 440.0,
 400.0,
 389.0,
 438.0,
 440.0,
 410.0,
 447.0,
 399.3333333333333,
 438.42264973081035,
 433.1835034190723,
 347.0,
 409.0,
 451.0,
 395.0,
 444.0,
 411.0,
 440.42264973081035,
 410.7113248654052,
 435.0,
 432.59175170953614,
 426.0,
 432.0,
 450.42264973081035,
 432.42264973081035,
 440.0,
 449.0,
 449.0,
 444.0,
 450.42264973081035,
 442.0,
 440.0,
 435.0,
 446.0,
 445.0,
 357.0,
 448.0,
 407.0,
 419.0,
 395.0,
 368.0,
 419.0,
 351.42264973081035,
 447.0,
 349.0,
 412.1835034190723,
 373.0,
 396.0,
 412.1835034190723,
 432.0,
 385.0,
 446.0,
 420.6666666666667,
 416.0,
 427.59175170953614,
 393.0,
 420.42264973081035,
 406.59175170953614,
 408.0,
 413.0,
 409.6666666666667,
 412.7113248654052,
 391.1835034190723,
 436.0,
 404.59175170953614,
 382.0,
 423.0,
 413.6666666666667,
 407.42264973081035,
 430.59175170953614,
 442.0,
 404.0,
 407.0,
 450.42264973081035,
 439.0,
 388.42264973081035,
 428.0,
 419.0,
 430.0,
 412.0,
 443.59175170953614,
 431.59175170953614,
 427.0,
 441.0,
 435.0,
 377.1835034190723,
 444.42264973081035,
 418.59175170953614,
 425.0,
 449.0,
 421.0,
 409.0,
 441.0,
 404.0,
 426.0,
 418.0,
 431.0,
 445.0,
 433.0,
 438.0,
 409.0,
 431.0,
 430.0,
 449.0,
 366.59175170953614,
 420.3333333333333,
 420.0,
 428.0,
 448.59175170953614,
 386.2254033307585,
 446.0,
 421.42264973081035,
 438.1835034190723,
 436.42264973081035,
 436.42264973081035,
 442.42264973081035,
 442.59175170953614,
 ...]